// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd7P8QjEBH9YKYZ5Fe5kSjL9BoMvSz0do',
    appId: '1:503845618952:web:eb246c0e6940dc53da18bd',
    messagingSenderId: '503845618952',
    projectId: 'social-media-c5f1e',
    authDomain: 'social-media-c5f1e.firebaseapp.com',
    storageBucket: 'social-media-c5f1e.firebasestorage.app',
    measurementId: 'G-EWPCZBML0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzzGhWj0Q22ub1h2vgxprhzxKK1_GNh6Y',
    appId: '1:503845618952:android:d3819d8f22c8146ada18bd',
    messagingSenderId: '503845618952',
    projectId: 'social-media-c5f1e',
    storageBucket: 'social-media-c5f1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD59uXMIP8YXJFwPMYAJGJW-2GXQc11wNs',
    appId: '1:503845618952:ios:c7e107460d564e10da18bd',
    messagingSenderId: '503845618952',
    projectId: 'social-media-c5f1e',
    storageBucket: 'social-media-c5f1e.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD59uXMIP8YXJFwPMYAJGJW-2GXQc11wNs',
    appId: '1:503845618952:ios:c7e107460d564e10da18bd',
    messagingSenderId: '503845618952',
    projectId: 'social-media-c5f1e',
    storageBucket: 'social-media-c5f1e.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd7P8QjEBH9YKYZ5Fe5kSjL9BoMvSz0do',
    appId: '1:503845618952:web:f738a11b5da2207cda18bd',
    messagingSenderId: '503845618952',
    projectId: 'social-media-c5f1e',
    authDomain: 'social-media-c5f1e.firebaseapp.com',
    storageBucket: 'social-media-c5f1e.firebasestorage.app',
    measurementId: 'G-4TTSWE4PFW',
  );
}
